name: Build and Push to Google Artifact Registry

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    environment: cicd-poc  # Specify the environment here

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Commit Hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to Use GAR
      run: |
        gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}-docker.pkg.dev

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/poc-backend:${{ env.COMMIT_HASH }} -f backend/Dockerfile backend
        docker push ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/poc-backend:${{ env.COMMIT_HASH }}

    - name: Build and Push HPC Frontend Image
      run: |
        docker build -t ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/poc-frontend-hpc:${{ env.COMMIT_HASH }} -f hpc/Dockerfile hpc
        docker push ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/poc-frontend-hpc:${{ env.COMMIT_HASH }}

    - name: Build and Push Default Frontend Image
      run: |
        docker build -t ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/poc-frontend-default:${{ env.COMMIT_HASH }} -f default/Dockerfile default
        docker push ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/poc-frontend-default:${{ env.COMMIT_HASH }}

    - name: Update Helm Chart Values
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

        # Clone the Helm chart repository
        git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.ORG }}/${{ secrets.HELM_REPO }}.git helm-repo
        cd helm-repo

        # Update the image tag in values.yaml for each service
        sed -i "s|tag: .*|tag: ${{ env.COMMIT_HASH }}|g" backend/values.yaml
        sed -i "s|tag: .*|tag: ${{ env.COMMIT_HASH }}|g" frontend-default/values.yaml
        sed -i "s|tag: .*|tag: ${{ env.COMMIT_HASH }}|g" frontend-hpc/values.yaml
        
        # Commit and push the changes
        git add .
        git commit -m "Update Helm chart values with new image tag: ${{ env.COMMIT_HASH }}"
        git push origin main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
